### ISSUE TITLE
how to set parameters of graphdr function

### ISSUE THREAD

**Issue by FADHLyemen** [jzthree/quasildr#3]
Hi 
I am using graphdr function with the following parameters;
The graphdr map looks strange than my umap, is there is a way to adjust for graphdr function?

`dr = graphdr(pca50, n_neighbors=15,_lambda=10, refine_threshold=10,refine_iter=6, no_rotation=False,rescale=False)`
My original umap looks like:
![image](https://user-images.githubusercontent.com/23288387/146066382-e94db241-58f3-4724-aef6-53b9a050b94e.png)

GraphDR CODE:
```
import plotnine
plotnine.options.figure_size=(20,15)
from plotnine import *
import warnings
warnings.simplefilter("ignore")


p = ggplot(pd.DataFrame({'x':-dr[:,0], 'y':dr[:,1], 
            'c': adata_T2D_HC_PT.obs['T2D_HC']}))+geom_point(aes(x='x', y='y', color='c'),size=0.01, alpha=1)+ guides(color=False)+  theme_void()+scale_color_hue(l=0.6,h=15/360,s=0.8)

p
```

WHICH looks like
![image](https://user-images.githubusercontent.com/23288387/146066619-357f2ec0-afd4-4097-b710-83b37b6a45ea.png)

**Comment by jzthree** [comment]
Thanks for trying GraphDR! The plot you showed seems to divide cells into two compartments. if that's not what you want, you can reduce `refine_threshold`  and `refine_iter` or turn it off to preserve more graph edges. 

Other parameters that will affect the look the most are `_lambda` (you can equivalently use `regularization` to set it and leave `_lambda` as default, using `regularization` is recommended because you usually need similar regularization parameters for different datasets but the proper `_lambda` can be dataset dependent). You may also decide how many PCs to use with GraphDR (for datasets with fewer reads, sometimes using a lower number of PC is better, but usually it is quite robust to the number of PCs).

If the first two dimensions do not give the best look for you, you can also try higher dimensions (I would also try with no_rotation=True to keep the PCA dimensions), or if you like, use 3D visualization. In addition, there are ways to find a good linear rotation that best separates your cell type, such as [linear discriminant analysis/LDA](https://scikit-learn.org/stable/modules/generated/sklearn.discriminant_analysis.LinearDiscriminantAnalysis.html).  An example that applies LDA with GraphDR could look like 
```
dr = graphdr(pca50, no_rotation=True, ...)
lda = LinearDiscriminantAnalysis()
dr_lda = lda.fit_transform(dr, celltype_label)
```

**Comment by FADHLyemen** [comment]
Thank you @jzthree 
Based on advice I changed the code, but still get a weird plot, any suggestions 
```
pca50 = adata_T2D_HC_PT.obsm['X_pca']
pca50 = pca50/pca50[:,0:10].std()
dr = graphdr(pca50, n_neighbors=15, refine_threshold=1,refine_iter=1, no_rotation=True,rescale=False)

import plotnine
plotnine.options.figure_size=(20,15)
from plotnine import *
import warnings
warnings.simplefilter("ignore")
p = ggplot(pd.DataFrame({'x':-dr[:,0], 'y':dr[:,1], 
            'c': adata_T2D_HC_PT.obs['T2D_HC']}))+geom_point(aes(x='x', y='y', color='c'),size=0.01, alpha=1)+ guides(color=False)+  theme_void()+scale_color_hue(l=0.6,h=15/360,s=0.8)
p
```

![image](https://user-images.githubusercontent.com/23288387/146074829-9f004eb8-0cc4-4be2-8b8e-08701a9eabde.png)

**Comment by jzthree** [comment]
Sorry, actually refine_threshold should be higher, not lower, in order to avoid cutting off too many graph edges. I would just set `refine_iter=0` as a starting point.  If it still looks similar, I would suspect this actually reflects what the data looks like (you can also compare it with what PCA shows).

**Comment by FADHLyemen** [comment]
```
pca50 = adata_T2D_HC_PT.obsm['X_pca']
pca50 = pca50/pca50[:,0].std()
dr = graphdr(pca50, n_neighbors=15, refine_threshold=10,refine_iter=0, no_rotation=True,rescale=False)

```


![image](https://user-images.githubusercontent.com/23288387/146079629-d51cc6e0-f354-4125-a3d4-6300d6337ac4.png)

**Comment by FADHLyemen** [comment]
@jzthree does it makes sense comparing graphdr and pca using `n_neighbors=15, refine_threshold=10,refine_iter=0, no_rotation=True,rescale=False`

**Comment by jzthree** [comment]
It should give results comparable with your input (which I assume was PCA). One way to check that is if you use smaller and smaller `regularization` parameter, it will gradually converge to your input. With regularization=0, it should just return your input.

**Comment by FADHLyemen** [comment]
@jzthree thank you, what is the default value of regularization? or it differs by dataset, 
which line of code to get it?

**Comment by jzthree** [comment]
The default now is `regularization=100` https://github.com/jzthree/quasildr/blob/c5ccfbafaed855e55bf8d0396591cb6e2a3e0384/quasildr/graphdr.py#L436
